name: Ansible Lint CI

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'
      - '**/roles/**'
      - 'playbooks/**'
  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - '**/roles/**'
      - 'playbooks/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and ansible-lint
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint .

