---
- name: Install system dependencies
  become: true
  dnf:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
    update_cache: yes

- name: Add Docker CE repository
  become: true
  command: >
    dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  become: true
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Configure Docker service
  become: true
  systemd:
    name: docker.service
    enabled: yes
    state: started

- name: Create docker group
  become: true
  group:
    name: docker
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ docker_user | default(ansible_user) }}"
    groups: docker
    append: yes

- name: Refresh group membership without hanging
  become: true
  command: sg docker -c "exit"
  changed_when: false

- name: Verify Docker access
  become: true
  command: docker ps
  register: docker_access_check
  changed_when: false
  retries: 3
  delay: 5
  until: docker_access_check.rc == 0

- name: Pull NGINX image
  become: true
  command: docker pull nginx:latest
  retries: 3
  delay: 5

- name: Ensure no conflicting container exists
  become: true
  command: docker rm -f nginx
  ignore_errors: yes
  changed_when: false

- name: Deploy NGINX container
  become: true
  command: >
    docker run -d --name nginx
    -p {{ docker_container_port | default('8080') }}:80
    --restart unless-stopped
    nginx:latest
  register: container_deploy
  retries: 2
  delay: 3

- name: Verify container status
  become: true
  shell: |
    docker inspect -f '{{ "{{" }}.State.Status{{ "}}" }}' nginx | grep -q running
  register: container_status
  until: container_status.rc == 0
  retries: 5
  delay: 2
  changed_when: false
