ansible_host: DataBaseServVM
ansible_user: ServTwoUser
custom_var_for_vm: "app server base config"
ansible_python_interpreter: /usr/bin/python3
db_user: DataBaseServVM_DB_User
db_password: "123456"
db_name: DataBaseServVM_DB
postgres_admin_password: "123456789"
