---
- name: Install PostgreSQL on DataBaseServVM
  hosts: DataBaseServVM
  become: true
  gather_facts: true
  tasks:

    - name: Install PostgreSQL server package
      dnf:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: /usr/bin/postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        enabled: true
        state: started
  
    - name: Install PostgreSQL server package
      dnf:
        name: postgresql-server
        state: present
      tags: install

