---
- name: Set up NGINX reverse proxy on WebServVM
  hosts: web
  become: true
  become_method: sudo
  become_user: ServOneUser 
  gather_facts: true
  vars:
    #    ansible_become_password: "123456"
  roles:
    - reverse_proxy

