---
- name: Configure AppServVM
  hosts: AppServVM
  become: true
  vars:
    docker_container_port: 8080
    docker_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  roles:
    - docker_setup

- name: Configure WebServVM
  hosts: WebServVM
  become: true
  roles:
    - reverse_proxy

- name: Configure DataBaseServVM
  hosts: DataBaseServVM
  become: true
  roles:
    - db_hardening
