---
- name: Configure AppServVM
  hosts: AppServVM
  become: true
  vars:
    docker_container_port: 8080
    docker_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  roles:
    - docker_setup

- name: Configure WebServVM
  hosts: WebServVM
  become: true
  roles:
    - reverse_proxy

- name: Configure DataBaseServVM
  hosts: DataBaseServVM
  become: true
  roles:
    - db_hardening

- name: Install PostgreSQL on DataBaseServVM
  hosts: DataBaseServVM
  become: true
  gather_facts: true
  tasks:
    - name: Install PostgreSQL server package
      dnf:
        name: postgresql-server
        state: present

    - name: Initialize PostgreSQL database
      command: /usr/bin/postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/PG_VERSION

    - name: Enable and start PostgreSQL service
      systemd:
        name: postgresql
        enabled: true
        state: started
