name: Docker App Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Docker App on WebServVM (Rocky/Alma Linux)
    runs-on: ubuntu-latest  # GitHub Actions runner (deployment orchestrator)
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up SSH private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
      - name: Add WebServVM to known_hosts
        run: |
          ssh-keyscan -p 22 ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          
      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip3 install ansible
          
      - name: Run Ansible Playbook for Docker Deployment
        run: |
          ansible-playbook playbooks/docker_app_deploy.yml \
            -i "${{ secrets.REMOTE_HOST }}," \
            --user "${{ secrets.REMOTE_USER }}" \
            --private-key ~/.ssh/id_ed25519
